// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: telemetry.proto

package telemetry

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TelemetryService_IngestTrace_FullMethodName  = "/telemetry.TelemetryService/IngestTrace"
	TelemetryService_IngestLog_FullMethodName    = "/telemetry.TelemetryService/IngestLog"
	TelemetryService_IngestMetric_FullMethodName = "/telemetry.TelemetryService/IngestMetric"
)

// TelemetryServiceClient is the client API for TelemetryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TelemetryServiceClient interface {
	IngestTrace(ctx context.Context, in *TraceIngestionRequest, opts ...grpc.CallOption) (*IngestionResponse, error)
	IngestLog(ctx context.Context, in *LogIngestionRequest, opts ...grpc.CallOption) (*IngestionResponse, error)
	IngestMetric(ctx context.Context, in *MetricIngestionRequest, opts ...grpc.CallOption) (*IngestionResponse, error)
}

type telemetryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTelemetryServiceClient(cc grpc.ClientConnInterface) TelemetryServiceClient {
	return &telemetryServiceClient{cc}
}

func (c *telemetryServiceClient) IngestTrace(ctx context.Context, in *TraceIngestionRequest, opts ...grpc.CallOption) (*IngestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestionResponse)
	err := c.cc.Invoke(ctx, TelemetryService_IngestTrace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryServiceClient) IngestLog(ctx context.Context, in *LogIngestionRequest, opts ...grpc.CallOption) (*IngestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestionResponse)
	err := c.cc.Invoke(ctx, TelemetryService_IngestLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryServiceClient) IngestMetric(ctx context.Context, in *MetricIngestionRequest, opts ...grpc.CallOption) (*IngestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestionResponse)
	err := c.cc.Invoke(ctx, TelemetryService_IngestMetric_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TelemetryServiceServer is the server API for TelemetryService service.
// All implementations must embed UnimplementedTelemetryServiceServer
// for forward compatibility.
type TelemetryServiceServer interface {
	IngestTrace(context.Context, *TraceIngestionRequest) (*IngestionResponse, error)
	IngestLog(context.Context, *LogIngestionRequest) (*IngestionResponse, error)
	IngestMetric(context.Context, *MetricIngestionRequest) (*IngestionResponse, error)
	mustEmbedUnimplementedTelemetryServiceServer()
}

// UnimplementedTelemetryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTelemetryServiceServer struct{}

func (UnimplementedTelemetryServiceServer) IngestTrace(context.Context, *TraceIngestionRequest) (*IngestionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IngestTrace not implemented")
}
func (UnimplementedTelemetryServiceServer) IngestLog(context.Context, *LogIngestionRequest) (*IngestionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IngestLog not implemented")
}
func (UnimplementedTelemetryServiceServer) IngestMetric(context.Context, *MetricIngestionRequest) (*IngestionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IngestMetric not implemented")
}
func (UnimplementedTelemetryServiceServer) mustEmbedUnimplementedTelemetryServiceServer() {}
func (UnimplementedTelemetryServiceServer) testEmbeddedByValue()                          {}

// UnsafeTelemetryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelemetryServiceServer will
// result in compilation errors.
type UnsafeTelemetryServiceServer interface {
	mustEmbedUnimplementedTelemetryServiceServer()
}

func RegisterTelemetryServiceServer(s grpc.ServiceRegistrar, srv TelemetryServiceServer) {
	// If the following call panics, it indicates UnimplementedTelemetryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TelemetryService_ServiceDesc, srv)
}

func _TelemetryService_IngestTrace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TraceIngestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).IngestTrace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryService_IngestTrace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).IngestTrace(ctx, req.(*TraceIngestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryService_IngestLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogIngestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).IngestLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryService_IngestLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).IngestLog(ctx, req.(*LogIngestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryService_IngestMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricIngestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).IngestMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryService_IngestMetric_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).IngestMetric(ctx, req.(*MetricIngestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TelemetryService_ServiceDesc is the grpc.ServiceDesc for TelemetryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelemetryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "telemetry.TelemetryService",
	HandlerType: (*TelemetryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IngestTrace",
			Handler:    _TelemetryService_IngestTrace_Handler,
		},
		{
			MethodName: "IngestLog",
			Handler:    _TelemetryService_IngestLog_Handler,
		},
		{
			MethodName: "IngestMetric",
			Handler:    _TelemetryService_IngestMetric_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "telemetry.proto",
}
