// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: telemetry.proto

package telemetry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Span struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpanId        string                 `protobuf:"bytes,1,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	ParentSpanId  string                 `protobuf:"bytes,2,opt,name=parent_span_id,json=parentSpanId,proto3" json:"parent_span_id,omitempty"`
	OperationName string                 `protobuf:"bytes,3,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	ServiceName   string                 `protobuf:"bytes,4,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	StartTimeNs   int64                  `protobuf:"varint,5,opt,name=start_time_ns,json=startTimeNs,proto3" json:"start_time_ns,omitempty"`
	DurationNs    int64                  `protobuf:"varint,6,opt,name=duration_ns,json=durationNs,proto3" json:"duration_ns,omitempty"`
	IsError       bool                   `protobuf:"varint,7,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,9,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Span) Reset() {
	*x = Span{}
	mi := &file_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Span) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Span) ProtoMessage() {}

func (x *Span) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Span.ProtoReflect.Descriptor instead.
func (*Span) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *Span) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *Span) GetParentSpanId() string {
	if x != nil {
		return x.ParentSpanId
	}
	return ""
}

func (x *Span) GetOperationName() string {
	if x != nil {
		return x.OperationName
	}
	return ""
}

func (x *Span) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Span) GetStartTimeNs() int64 {
	if x != nil {
		return x.StartTimeNs
	}
	return 0
}

func (x *Span) GetDurationNs() int64 {
	if x != nil {
		return x.DurationNs
	}
	return 0
}

func (x *Span) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *Span) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *Span) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type MetricDataPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetricName    string                 `protobuf:"bytes,1,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimestampNs   int64                  `protobuf:"varint,4,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	MetricType    string                 `protobuf:"bytes,5,opt,name=metric_type,json=metricType,proto3" json:"metric_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricDataPoint) Reset() {
	*x = MetricDataPoint{}
	mi := &file_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricDataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricDataPoint) ProtoMessage() {}

func (x *MetricDataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricDataPoint.ProtoReflect.Descriptor instead.
func (*MetricDataPoint) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *MetricDataPoint) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *MetricDataPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricDataPoint) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *MetricDataPoint) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *MetricDataPoint) GetMetricType() string {
	if x != nil {
		return x.MetricType
	}
	return ""
}

type TraceIngestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Spans         []*Span                `protobuf:"bytes,2,rep,name=spans,proto3" json:"spans,omitempty"`
	SourceService string                 `protobuf:"bytes,3,opt,name=source_service,json=sourceService,proto3" json:"source_service,omitempty"`
	IngestedAtNs  int64                  `protobuf:"varint,4,opt,name=ingested_at_ns,json=ingestedAtNs,proto3" json:"ingested_at_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceIngestionRequest) Reset() {
	*x = TraceIngestionRequest{}
	mi := &file_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceIngestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceIngestionRequest) ProtoMessage() {}

func (x *TraceIngestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceIngestionRequest.ProtoReflect.Descriptor instead.
func (*TraceIngestionRequest) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *TraceIngestionRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *TraceIngestionRequest) GetSpans() []*Span {
	if x != nil {
		return x.Spans
	}
	return nil
}

func (x *TraceIngestionRequest) GetSourceService() string {
	if x != nil {
		return x.SourceService
	}
	return ""
}

func (x *TraceIngestionRequest) GetIngestedAtNs() int64 {
	if x != nil {
		return x.IngestedAtNs
	}
	return 0
}

type LogIngestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogId         string                 `protobuf:"bytes,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Level         string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	TraceId       string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId        string                 `protobuf:"bytes,6,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	TimestampNs   int64                  `protobuf:"varint,7,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,8,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogIngestionRequest) Reset() {
	*x = LogIngestionRequest{}
	mi := &file_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogIngestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogIngestionRequest) ProtoMessage() {}

func (x *LogIngestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogIngestionRequest.ProtoReflect.Descriptor instead.
func (*LogIngestionRequest) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *LogIngestionRequest) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

func (x *LogIngestionRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *LogIngestionRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogIngestionRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogIngestionRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *LogIngestionRequest) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *LogIngestionRequest) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *LogIngestionRequest) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type MetricIngestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceService string                 `protobuf:"bytes,1,opt,name=source_service,json=sourceService,proto3" json:"source_service,omitempty"`
	Points        []*MetricDataPoint     `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty"`
	CollectedAtNs int64                  `protobuf:"varint,3,opt,name=collected_at_ns,json=collectedAtNs,proto3" json:"collected_at_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricIngestionRequest) Reset() {
	*x = MetricIngestionRequest{}
	mi := &file_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricIngestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricIngestionRequest) ProtoMessage() {}

func (x *MetricIngestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricIngestionRequest.ProtoReflect.Descriptor instead.
func (*MetricIngestionRequest) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *MetricIngestionRequest) GetSourceService() string {
	if x != nil {
		return x.SourceService
	}
	return ""
}

func (x *MetricIngestionRequest) GetPoints() []*MetricDataPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *MetricIngestionRequest) GetCollectedAtNs() int64 {
	if x != nil {
		return x.CollectedAtNs
	}
	return 0
}

type IngestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	IngestionId   string                 `protobuf:"bytes,2,opt,name=ingestion_id,json=ingestionId,proto3" json:"ingestion_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	TimestampNs   int64                  `protobuf:"varint,4,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestionResponse) Reset() {
	*x = IngestionResponse{}
	mi := &file_telemetry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestionResponse) ProtoMessage() {}

func (x *IngestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestionResponse.ProtoReflect.Descriptor instead.
func (*IngestionResponse) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{5}
}

func (x *IngestionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *IngestionResponse) GetIngestionId() string {
	if x != nil {
		return x.IngestionId
	}
	return ""
}

func (x *IngestionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *IngestionResponse) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

type IncidentNotification struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IncidentId         string                 `protobuf:"bytes,1,opt,name=incident_id,json=incidentId,proto3" json:"incident_id,omitempty"`
	TriggerType        string                 `protobuf:"bytes,2,opt,name=trigger_type,json=triggerType,proto3" json:"trigger_type,omitempty"`
	TriggerDescription string                 `protobuf:"bytes,3,opt,name=trigger_description,json=triggerDescription,proto3" json:"trigger_description,omitempty"`
	Services           []string               `protobuf:"bytes,4,rep,name=services,proto3" json:"services,omitempty"`
	DetectedAtNs       int64                  `protobuf:"varint,5,opt,name=detected_at_ns,json=detectedAtNs,proto3" json:"detected_at_ns,omitempty"`
	TriggerValue       float64                `protobuf:"fixed64,6,opt,name=trigger_value,json=triggerValue,proto3" json:"trigger_value,omitempty"`
	TriggerThreshold   float64                `protobuf:"fixed64,7,opt,name=trigger_threshold,json=triggerThreshold,proto3" json:"trigger_threshold,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *IncidentNotification) Reset() {
	*x = IncidentNotification{}
	mi := &file_telemetry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncidentNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncidentNotification) ProtoMessage() {}

func (x *IncidentNotification) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncidentNotification.ProtoReflect.Descriptor instead.
func (*IncidentNotification) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{6}
}

func (x *IncidentNotification) GetIncidentId() string {
	if x != nil {
		return x.IncidentId
	}
	return ""
}

func (x *IncidentNotification) GetTriggerType() string {
	if x != nil {
		return x.TriggerType
	}
	return ""
}

func (x *IncidentNotification) GetTriggerDescription() string {
	if x != nil {
		return x.TriggerDescription
	}
	return ""
}

func (x *IncidentNotification) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *IncidentNotification) GetDetectedAtNs() int64 {
	if x != nil {
		return x.DetectedAtNs
	}
	return 0
}

func (x *IncidentNotification) GetTriggerValue() float64 {
	if x != nil {
		return x.TriggerValue
	}
	return 0
}

func (x *IncidentNotification) GetTriggerThreshold() float64 {
	if x != nil {
		return x.TriggerThreshold
	}
	return 0
}

var File_telemetry_proto protoreflect.FileDescriptor

const file_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x0ftelemetry.proto\x12\ttelemetry\"\x94\x03\n" +
	"\x04Span\x12\x17\n" +
	"\aspan_id\x18\x01 \x01(\tR\x06spanId\x12$\n" +
	"\x0eparent_span_id\x18\x02 \x01(\tR\fparentSpanId\x12%\n" +
	"\x0eoperation_name\x18\x03 \x01(\tR\roperationName\x12!\n" +
	"\fservice_name\x18\x04 \x01(\tR\vserviceName\x12\"\n" +
	"\rstart_time_ns\x18\x05 \x01(\x03R\vstartTimeNs\x12\x1f\n" +
	"\vduration_ns\x18\x06 \x01(\x03R\n" +
	"durationNs\x12\x19\n" +
	"\bis_error\x18\a \x01(\bR\aisError\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\x12?\n" +
	"\n" +
	"attributes\x18\t \x03(\v2\x1f.telemetry.Span.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x02\n" +
	"\x0fMetricDataPoint\x12\x1f\n" +
	"\vmetric_name\x18\x01 \x01(\tR\n" +
	"metricName\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12>\n" +
	"\x06labels\x18\x03 \x03(\v2&.telemetry.MetricDataPoint.LabelsEntryR\x06labels\x12!\n" +
	"\ftimestamp_ns\x18\x04 \x01(\x03R\vtimestampNs\x12\x1f\n" +
	"\vmetric_type\x18\x05 \x01(\tR\n" +
	"metricType\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa6\x01\n" +
	"\x15TraceIngestionRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12%\n" +
	"\x05spans\x18\x02 \x03(\v2\x0f.telemetry.SpanR\x05spans\x12%\n" +
	"\x0esource_service\x18\x03 \x01(\tR\rsourceService\x12$\n" +
	"\x0eingested_at_ns\x18\x04 \x01(\x03R\fingestedAtNs\"\xd5\x02\n" +
	"\x13LogIngestionRequest\x12\x15\n" +
	"\x06log_id\x18\x01 \x01(\tR\x05logId\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x06 \x01(\tR\x06spanId\x12!\n" +
	"\ftimestamp_ns\x18\a \x01(\x03R\vtimestampNs\x12B\n" +
	"\x06fields\x18\b \x03(\v2*.telemetry.LogIngestionRequest.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9b\x01\n" +
	"\x16MetricIngestionRequest\x12%\n" +
	"\x0esource_service\x18\x01 \x01(\tR\rsourceService\x122\n" +
	"\x06points\x18\x02 \x03(\v2\x1a.telemetry.MetricDataPointR\x06points\x12&\n" +
	"\x0fcollected_at_ns\x18\x03 \x01(\x03R\rcollectedAtNs\"\x8b\x01\n" +
	"\x11IngestionResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12!\n" +
	"\fingestion_id\x18\x02 \x01(\tR\vingestionId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12!\n" +
	"\ftimestamp_ns\x18\x04 \x01(\x03R\vtimestampNs\"\x9f\x02\n" +
	"\x14IncidentNotification\x12\x1f\n" +
	"\vincident_id\x18\x01 \x01(\tR\n" +
	"incidentId\x12!\n" +
	"\ftrigger_type\x18\x02 \x01(\tR\vtriggerType\x12/\n" +
	"\x13trigger_description\x18\x03 \x01(\tR\x12triggerDescription\x12\x1a\n" +
	"\bservices\x18\x04 \x03(\tR\bservices\x12$\n" +
	"\x0edetected_at_ns\x18\x05 \x01(\x03R\fdetectedAtNs\x12#\n" +
	"\rtrigger_value\x18\x06 \x01(\x01R\ftriggerValue\x12+\n" +
	"\x11trigger_threshold\x18\a \x01(\x01R\x10triggerThreshold2\xfd\x01\n" +
	"\x10TelemetryService\x12M\n" +
	"\vIngestTrace\x12 .telemetry.TraceIngestionRequest\x1a\x1c.telemetry.IngestionResponse\x12I\n" +
	"\tIngestLog\x12\x1e.telemetry.LogIngestionRequest\x1a\x1c.telemetry.IngestionResponse\x12O\n" +
	"\fIngestMetric\x12!.telemetry.MetricIngestionRequest\x1a\x1c.telemetry.IngestionResponseB3Z1github.com/sujithm/ghost-debugger/proto/telemetryb\x06proto3"

var (
	file_telemetry_proto_rawDescOnce sync.Once
	file_telemetry_proto_rawDescData []byte
)

func file_telemetry_proto_rawDescGZIP() []byte {
	file_telemetry_proto_rawDescOnce.Do(func() {
		file_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)))
	})
	return file_telemetry_proto_rawDescData
}

var file_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_telemetry_proto_goTypes = []any{
	(*Span)(nil),                   // 0: telemetry.Span
	(*MetricDataPoint)(nil),        // 1: telemetry.MetricDataPoint
	(*TraceIngestionRequest)(nil),  // 2: telemetry.TraceIngestionRequest
	(*LogIngestionRequest)(nil),    // 3: telemetry.LogIngestionRequest
	(*MetricIngestionRequest)(nil), // 4: telemetry.MetricIngestionRequest
	(*IngestionResponse)(nil),      // 5: telemetry.IngestionResponse
	(*IncidentNotification)(nil),   // 6: telemetry.IncidentNotification
	nil,                            // 7: telemetry.Span.AttributesEntry
	nil,                            // 8: telemetry.MetricDataPoint.LabelsEntry
	nil,                            // 9: telemetry.LogIngestionRequest.FieldsEntry
}
var file_telemetry_proto_depIdxs = []int32{
	7, // 0: telemetry.Span.attributes:type_name -> telemetry.Span.AttributesEntry
	8, // 1: telemetry.MetricDataPoint.labels:type_name -> telemetry.MetricDataPoint.LabelsEntry
	0, // 2: telemetry.TraceIngestionRequest.spans:type_name -> telemetry.Span
	9, // 3: telemetry.LogIngestionRequest.fields:type_name -> telemetry.LogIngestionRequest.FieldsEntry
	1, // 4: telemetry.MetricIngestionRequest.points:type_name -> telemetry.MetricDataPoint
	2, // 5: telemetry.TelemetryService.IngestTrace:input_type -> telemetry.TraceIngestionRequest
	3, // 6: telemetry.TelemetryService.IngestLog:input_type -> telemetry.LogIngestionRequest
	4, // 7: telemetry.TelemetryService.IngestMetric:input_type -> telemetry.MetricIngestionRequest
	5, // 8: telemetry.TelemetryService.IngestTrace:output_type -> telemetry.IngestionResponse
	5, // 9: telemetry.TelemetryService.IngestLog:output_type -> telemetry.IngestionResponse
	5, // 10: telemetry.TelemetryService.IngestMetric:output_type -> telemetry.IngestionResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_telemetry_proto_init() }
func file_telemetry_proto_init() {
	if File_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_telemetry_proto_goTypes,
		DependencyIndexes: file_telemetry_proto_depIdxs,
		MessageInfos:      file_telemetry_proto_msgTypes,
	}.Build()
	File_telemetry_proto = out.File
	file_telemetry_proto_goTypes = nil
	file_telemetry_proto_depIdxs = nil
}
