# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from agents.proto import telemetry_pb2 as telemetry__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in telemetry_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TelemetryServiceStub:
    """═══════════════════════════════════════════════════════════════════════════════
    SERVICE DEFINITION
    ═══════════════════════════════════════════════════════════════════════════════

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngestTrace = channel.unary_unary(
                '/telemetry.TelemetryService/IngestTrace',
                request_serializer=telemetry__pb2.TraceIngestionRequest.SerializeToString,
                response_deserializer=telemetry__pb2.IngestionResponse.FromString,
                _registered_method=True)
        self.IngestLog = channel.unary_unary(
                '/telemetry.TelemetryService/IngestLog',
                request_serializer=telemetry__pb2.LogIngestionRequest.SerializeToString,
                response_deserializer=telemetry__pb2.IngestionResponse.FromString,
                _registered_method=True)
        self.IngestMetric = channel.unary_unary(
                '/telemetry.TelemetryService/IngestMetric',
                request_serializer=telemetry__pb2.MetricIngestionRequest.SerializeToString,
                response_deserializer=telemetry__pb2.IngestionResponse.FromString,
                _registered_method=True)


class TelemetryServiceServicer:
    """═══════════════════════════════════════════════════════════════════════════════
    SERVICE DEFINITION
    ═══════════════════════════════════════════════════════════════════════════════

    """

    def IngestTrace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestLog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestMetric(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TelemetryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IngestTrace': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestTrace,
                    request_deserializer=telemetry__pb2.TraceIngestionRequest.FromString,
                    response_serializer=telemetry__pb2.IngestionResponse.SerializeToString,
            ),
            'IngestLog': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestLog,
                    request_deserializer=telemetry__pb2.LogIngestionRequest.FromString,
                    response_serializer=telemetry__pb2.IngestionResponse.SerializeToString,
            ),
            'IngestMetric': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestMetric,
                    request_deserializer=telemetry__pb2.MetricIngestionRequest.FromString,
                    response_serializer=telemetry__pb2.IngestionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'telemetry.TelemetryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('telemetry.TelemetryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TelemetryService:
    """═══════════════════════════════════════════════════════════════════════════════
    SERVICE DEFINITION
    ═══════════════════════════════════════════════════════════════════════════════

    """

    @staticmethod
    def IngestTrace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/telemetry.TelemetryService/IngestTrace',
            telemetry__pb2.TraceIngestionRequest.SerializeToString,
            telemetry__pb2.IngestionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/telemetry.TelemetryService/IngestLog',
            telemetry__pb2.LogIngestionRequest.SerializeToString,
            telemetry__pb2.IngestionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestMetric(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/telemetry.TelemetryService/IngestMetric',
            telemetry__pb2.MetricIngestionRequest.SerializeToString,
            telemetry__pb2.IngestionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
