import logging
from datetime import datetime, timezone
from agents.state.postmortem_state import PostmortemState
from agents.shared.llm import get_llm
from agents.shared.node_utils import build_base_messages, safe_append, format_state_for_prompt, now_iso

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = """You are the POSTMORTEM WRITER in an automated incident analysis system.

Your job is to write a clear, structured postmortem report from the analysis
findings. This report will be read by engineers and engineering managers.

TONE AND STYLE:
- Factual and precise — use specific numbers and timestamps
- Blameless — focus on systems and processes, not individuals
- Actionable — every section leads to clear next steps
- Honest about uncertainty — note confidence levels and data gaps

The postmortem MUST follow this exact structure (use these exact headers):

# Postmortem: [Brief Incident Title]

## Incident Summary
| Field | Value |
|-------|-------|
| Incident ID | [id] |
| Severity | [SEV1/SEV2/SEV3] |
| Status | Resolved |
| Detected At | [timestamp] |
| Duration | [estimated duration] |
| Affected Services | [comma-separated] |
| Root Cause Confidence | [X%] |

## Impact
[2-3 sentences describing user-visible impact and scope]

## Timeline
| Time | Event | Signal Source |
|------|-------|---------------|
| [timestamp] | [event description] | trace/log/metric |

## Root Cause
[Clear root cause statement]

**Confidence:** [X%]

[2-3 paragraph explanation of the root cause mechanism]

## Contributing Factors
- [factor 1]
- [factor 2]
- [factor 3]

## Blast Radius
**Affected:** [services and users that experienced impact]
**Not Affected:** [services that were healthy throughout]

## Signal Analysis
### Distributed Traces
[trace findings summary]

### Logs
[log findings summary]

### Metrics
[metric findings summary]

## Similar Past Incidents
[For each similar incident: ID, similarity score, root cause, resolution time]
If none: "No similar incidents found in historical database."

## Action Items
### Immediate (< 24 hours)
- [ ] [action item]
### Short-term (< 1 week)
- [ ] [action item]
### Long-term (< 1 month)
- [ ] [action item]

## Data Gaps
[Only include if signal_completeness is 'partial']
[Explain which signals were unavailable and impact on confidence]
If all signals available: "All three observability signals were available during this incident."

---
*Report generated by Ghost Debugger at [timestamp]*
*Signal completeness: [full/partial]*"""


def postmortem_writer_node(state: PostmortemState) -> dict:
    logger.info(f"[postmortem_writer] starting — incident: {state['incident_id']}")

    signal_completeness = "full"
    missing_signals = []
    if not state.get("trace_had_error"):
        missing_signals.append("distributed traces")
        signal_completeness = "partial"
    if not state.get("log_had_error"):
        missing_signals.append("logs")
        signal_completeness = "partial"
    if not state.get("metric_had_error"):
        missing_signals.append("metrics")
        signal_completeness = "partial"

    all_findings = format_state_for_prompt(state, [
        "triage_findings", "triage_severity", "triage_confirmed_services",
        "trace_findings", "trace_first_error_service", "trace_first_error_time",
        "trace_cascade_path",
        "log_findings", "log_error_patterns", "log_first_error_time",
        "metric_findings", "metric_saturated_resource", "metric_anomaly_details",
        "correlation_summary", "causal_chain",
        "root_cause", "root_cause_confidence", "contributing_factors",
        "similar_incidents",
    ])

    similar_incident_details = ""
    if state.get("similar_incidents"):
        similar_incident_details = (
            f"Similar incidents from RAG: {', '.join(state['similar_incidents'])}"
        )

    now = datetime.now(tz=timezone.utc).isoformat()

    human_prompt = f"""POSTMORTEM WRITING TASK:

Incident ID: {state['incident_id']}
Detected At: {state.get('detected_at', 'Unknown')}
Signal Completeness: {signal_completeness}
Missing Signals: {', '.join(missing_signals) if missing_signals else 'None'}

ALL ANALYSIS FINDINGS:
{all_findings}

{similar_incident_details}

Write the complete postmortem report following the exact structure in your instructions.
Use the causal chain for the timeline table.
Use the root_cause and contributing_factors for those sections.
Generate realistic, specific action items based on the root cause and contributing factors.
Current time: {now}"""

    llm = get_llm()
    messages = build_base_messages(SYSTEM_PROMPT, human_prompt)

    try:
        response = llm.invoke(messages)
        report = response.content or ""

        if not report.startswith("# Postmortem"):
            report = f"# Postmortem: {state.get('trigger_description', 'Incident Analysis')}\n\n" + report

        logger.info(f"[postmortem_writer] complete — report length: {len(report)} chars")

        return {
            "postmortem_report": report,
            "signal_completeness": signal_completeness,
            "completed_agents": safe_append(state.get("completed_agents", []), "postmortem_writer"),
            "analysis_end_at": now_iso(),
        }

    except Exception as e:
        logger.error(f"[postmortem_writer] failed: {e}")

        fallback_report = _generate_fallback_report(state, signal_completeness, str(e))

        return {
            "postmortem_report": fallback_report,
            "signal_completeness": signal_completeness,
            "completed_agents": safe_append(state.get("completed_agents", []), "postmortem_writer"),
            "failed_agents": safe_append(state.get("failed_agents", []), "postmortem_writer"),
            "errors": safe_append(state.get("errors", []), f"[postmortem_writer] {type(e).__name__}: {str(e)[:200]}"),
        }


def _generate_fallback_report(state: PostmortemState, completeness: str, error: str) -> str:
    now = datetime.now(tz=timezone.utc).isoformat()
    services = ", ".join(
        state.get("triage_confirmed_services") or state.get("affected_services", [])
    )
    root_cause = state.get("root_cause", "Under investigation")
    confidence = state.get("root_cause_confidence", 0.0)
    causal_chain = state.get("causal_chain", [])
    contributing = state.get("contributing_factors", [])

    chain_lines = "\n".join(
        f"| {step} | — | — |" for step in causal_chain
    ) or "| — | No causal chain available | — |"

    factor_lines = "\n".join(f"- {f}" for f in contributing) or "- Not determined"

    return f"""# Postmortem: {state.get('trigger_description', 'Incident')}

## Incident Summary
| Field | Value |
|-------|-------|
| Incident ID | {state['incident_id']} |
| Severity | {state.get('triage_severity', 'UNKNOWN')} |
| Detected At | {state.get('detected_at', 'Unknown')} |
| Affected Services | {services} |
| Root Cause Confidence | {confidence * 100:.0f}% |
| Signal Completeness | {completeness} |

## Root Cause
{root_cause}

## Timeline
| Time | Event | Signal |
|------|-------|--------|
{chain_lines}

## Contributing Factors
{factor_lines}

## Data Gaps
Signal completeness: {completeness}.
Postmortem writer encountered an error: {error[:200]}.
All raw findings are preserved in the incident state.

---
*Fallback report generated by Ghost Debugger at {now}*"""
