// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: agent.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalysisRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IncidentId         string                 `protobuf:"bytes,1,opt,name=incident_id,json=incidentId,proto3" json:"incident_id,omitempty"`
	TriggerType        string                 `protobuf:"bytes,2,opt,name=trigger_type,json=triggerType,proto3" json:"trigger_type,omitempty"`
	TriggerDescription string                 `protobuf:"bytes,3,opt,name=trigger_description,json=triggerDescription,proto3" json:"trigger_description,omitempty"`
	Services           []string               `protobuf:"bytes,4,rep,name=services,proto3" json:"services,omitempty"`
	DetectedAtNs       int64                  `protobuf:"varint,5,opt,name=detected_at_ns,json=detectedAtNs,proto3" json:"detected_at_ns,omitempty"`
	AnalysisWindowNs   int64                  `protobuf:"varint,6,opt,name=analysis_window_ns,json=analysisWindowNs,proto3" json:"analysis_window_ns,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AnalysisRequest) Reset() {
	*x = AnalysisRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisRequest) ProtoMessage() {}

func (x *AnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisRequest.ProtoReflect.Descriptor instead.
func (*AnalysisRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AnalysisRequest) GetIncidentId() string {
	if x != nil {
		return x.IncidentId
	}
	return ""
}

func (x *AnalysisRequest) GetTriggerType() string {
	if x != nil {
		return x.TriggerType
	}
	return ""
}

func (x *AnalysisRequest) GetTriggerDescription() string {
	if x != nil {
		return x.TriggerDescription
	}
	return ""
}

func (x *AnalysisRequest) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *AnalysisRequest) GetDetectedAtNs() int64 {
	if x != nil {
		return x.DetectedAtNs
	}
	return 0
}

func (x *AnalysisRequest) GetAnalysisWindowNs() int64 {
	if x != nil {
		return x.AnalysisWindowNs
	}
	return 0
}

type AgentFinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentName     string                 `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	Finding       string                 `protobuf:"bytes,2,opt,name=finding,proto3" json:"finding,omitempty"`
	Confidence    float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	CompletedAt   int64                  `protobuf:"varint,4,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	HadError      bool                   `protobuf:"varint,5,opt,name=had_error,json=hadError,proto3" json:"had_error,omitempty"`
	ErrorDetail   string                 `protobuf:"bytes,6,opt,name=error_detail,json=errorDetail,proto3" json:"error_detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentFinding) Reset() {
	*x = AgentFinding{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentFinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentFinding) ProtoMessage() {}

func (x *AgentFinding) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentFinding.ProtoReflect.Descriptor instead.
func (*AgentFinding) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentFinding) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *AgentFinding) GetFinding() string {
	if x != nil {
		return x.Finding
	}
	return ""
}

func (x *AgentFinding) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *AgentFinding) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

func (x *AgentFinding) GetHadError() bool {
	if x != nil {
		return x.HadError
	}
	return false
}

func (x *AgentFinding) GetErrorDetail() string {
	if x != nil {
		return x.ErrorDetail
	}
	return ""
}

type AnalysisResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	IncidentId          string                 `protobuf:"bytes,1,opt,name=incident_id,json=incidentId,proto3" json:"incident_id,omitempty"`
	Findings            []*AgentFinding        `protobuf:"bytes,2,rep,name=findings,proto3" json:"findings,omitempty"`
	RootCause           string                 `protobuf:"bytes,3,opt,name=root_cause,json=rootCause,proto3" json:"root_cause,omitempty"`
	RootCauseConfidence float64                `protobuf:"fixed64,4,opt,name=root_cause_confidence,json=rootCauseConfidence,proto3" json:"root_cause_confidence,omitempty"`
	PostmortemMarkdown  string                 `protobuf:"bytes,5,opt,name=postmortem_markdown,json=postmortemMarkdown,proto3" json:"postmortem_markdown,omitempty"`
	SimilarIncidents    []string               `protobuf:"bytes,6,rep,name=similar_incidents,json=similarIncidents,proto3" json:"similar_incidents,omitempty"`
	AnalysisDurationMs  int64                  `protobuf:"varint,7,opt,name=analysis_duration_ms,json=analysisDurationMs,proto3" json:"analysis_duration_ms,omitempty"`
	Status              string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	SignalCompleteness  string                 `protobuf:"bytes,9,opt,name=signal_completeness,json=signalCompleteness,proto3" json:"signal_completeness,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AnalysisResponse) Reset() {
	*x = AnalysisResponse{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisResponse) ProtoMessage() {}

func (x *AnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisResponse.ProtoReflect.Descriptor instead.
func (*AnalysisResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AnalysisResponse) GetIncidentId() string {
	if x != nil {
		return x.IncidentId
	}
	return ""
}

func (x *AnalysisResponse) GetFindings() []*AgentFinding {
	if x != nil {
		return x.Findings
	}
	return nil
}

func (x *AnalysisResponse) GetRootCause() string {
	if x != nil {
		return x.RootCause
	}
	return ""
}

func (x *AnalysisResponse) GetRootCauseConfidence() float64 {
	if x != nil {
		return x.RootCauseConfidence
	}
	return 0
}

func (x *AnalysisResponse) GetPostmortemMarkdown() string {
	if x != nil {
		return x.PostmortemMarkdown
	}
	return ""
}

func (x *AnalysisResponse) GetSimilarIncidents() []string {
	if x != nil {
		return x.SimilarIncidents
	}
	return nil
}

func (x *AnalysisResponse) GetAnalysisDurationMs() int64 {
	if x != nil {
		return x.AnalysisDurationMs
	}
	return 0
}

func (x *AnalysisResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AnalysisResponse) GetSignalCompleteness() string {
	if x != nil {
		return x.SignalCompleteness
	}
	return ""
}

type AnalysisProgressUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IncidentId    string                 `protobuf:"bytes,1,opt,name=incident_id,json=incidentId,proto3" json:"incident_id,omitempty"`
	AgentName     string                 `protobuf:"bytes,2,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Detail        string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	TimestampNs   int64                  `protobuf:"varint,5,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisProgressUpdate) Reset() {
	*x = AnalysisProgressUpdate{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisProgressUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisProgressUpdate) ProtoMessage() {}

func (x *AnalysisProgressUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisProgressUpdate.ProtoReflect.Descriptor instead.
func (*AnalysisProgressUpdate) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *AnalysisProgressUpdate) GetIncidentId() string {
	if x != nil {
		return x.IncidentId
	}
	return ""
}

func (x *AnalysisProgressUpdate) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *AnalysisProgressUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AnalysisProgressUpdate) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *AnalysisProgressUpdate) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	SentAt        int64                  `protobuf:"varint,2,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PingRequest) GetSentAt() int64 {
	if x != nil {
		return x.SentAt
	}
	return 0
}

type PongResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OriginalMessage string                 `protobuf:"bytes,1,opt,name=original_message,json=originalMessage,proto3" json:"original_message,omitempty"`
	ServerLanguage  string                 `protobuf:"bytes,2,opt,name=server_language,json=serverLanguage,proto3" json:"server_language,omitempty"`
	ReceivedAt      int64                  `protobuf:"varint,3,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	RepliedAt       int64                  `protobuf:"varint,4,opt,name=replied_at,json=repliedAt,proto3" json:"replied_at,omitempty"`
	RoundTripMs     int64                  `protobuf:"varint,5,opt,name=round_trip_ms,json=roundTripMs,proto3" json:"round_trip_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PongResponse) Reset() {
	*x = PongResponse{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongResponse) ProtoMessage() {}

func (x *PongResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongResponse.ProtoReflect.Descriptor instead.
func (*PongResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *PongResponse) GetOriginalMessage() string {
	if x != nil {
		return x.OriginalMessage
	}
	return ""
}

func (x *PongResponse) GetServerLanguage() string {
	if x != nil {
		return x.ServerLanguage
	}
	return ""
}

func (x *PongResponse) GetReceivedAt() int64 {
	if x != nil {
		return x.ReceivedAt
	}
	return 0
}

func (x *PongResponse) GetRepliedAt() int64 {
	if x != nil {
		return x.RepliedAt
	}
	return 0
}

func (x *PongResponse) GetRoundTripMs() int64 {
	if x != nil {
		return x.RoundTripMs
	}
	return 0
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x05agent\"\xf6\x01\n" +
	"\x0fAnalysisRequest\x12\x1f\n" +
	"\vincident_id\x18\x01 \x01(\tR\n" +
	"incidentId\x12!\n" +
	"\ftrigger_type\x18\x02 \x01(\tR\vtriggerType\x12/\n" +
	"\x13trigger_description\x18\x03 \x01(\tR\x12triggerDescription\x12\x1a\n" +
	"\bservices\x18\x04 \x03(\tR\bservices\x12$\n" +
	"\x0edetected_at_ns\x18\x05 \x01(\x03R\fdetectedAtNs\x12,\n" +
	"\x12analysis_window_ns\x18\x06 \x01(\x03R\x10analysisWindowNs\"\xca\x01\n" +
	"\fAgentFinding\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\x12\x18\n" +
	"\afinding\x18\x02 \x01(\tR\afinding\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12!\n" +
	"\fcompleted_at\x18\x04 \x01(\x03R\vcompletedAt\x12\x1b\n" +
	"\thad_error\x18\x05 \x01(\bR\bhadError\x12!\n" +
	"\ferror_detail\x18\x06 \x01(\tR\verrorDetail\"\x90\x03\n" +
	"\x10AnalysisResponse\x12\x1f\n" +
	"\vincident_id\x18\x01 \x01(\tR\n" +
	"incidentId\x12/\n" +
	"\bfindings\x18\x02 \x03(\v2\x13.agent.AgentFindingR\bfindings\x12\x1d\n" +
	"\n" +
	"root_cause\x18\x03 \x01(\tR\trootCause\x122\n" +
	"\x15root_cause_confidence\x18\x04 \x01(\x01R\x13rootCauseConfidence\x12/\n" +
	"\x13postmortem_markdown\x18\x05 \x01(\tR\x12postmortemMarkdown\x12+\n" +
	"\x11similar_incidents\x18\x06 \x03(\tR\x10similarIncidents\x120\n" +
	"\x14analysis_duration_ms\x18\a \x01(\x03R\x12analysisDurationMs\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12/\n" +
	"\x13signal_completeness\x18\t \x01(\tR\x12signalCompleteness\"\xab\x01\n" +
	"\x16AnalysisProgressUpdate\x12\x1f\n" +
	"\vincident_id\x18\x01 \x01(\tR\n" +
	"incidentId\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x02 \x01(\tR\tagentName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\x12!\n" +
	"\ftimestamp_ns\x18\x05 \x01(\x03R\vtimestampNs\"@\n" +
	"\vPingRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x17\n" +
	"\asent_at\x18\x02 \x01(\x03R\x06sentAt\"\xc6\x01\n" +
	"\fPongResponse\x12)\n" +
	"\x10original_message\x18\x01 \x01(\tR\x0foriginalMessage\x12'\n" +
	"\x0fserver_language\x18\x02 \x01(\tR\x0eserverLanguage\x12\x1f\n" +
	"\vreceived_at\x18\x03 \x01(\x03R\n" +
	"receivedAt\x12\x1d\n" +
	"\n" +
	"replied_at\x18\x04 \x01(\x03R\trepliedAt\x12\"\n" +
	"\rround_trip_ms\x18\x05 \x01(\x03R\vroundTripMs2\xdb\x01\n" +
	"\fAgentService\x12B\n" +
	"\x0fAnalyzeIncident\x12\x16.agent.AnalysisRequest\x1a\x17.agent.AnalysisResponse\x12V\n" +
	"\x1bAnalyzeIncidentWithProgress\x12\x16.agent.AnalysisRequest\x1a\x1d.agent.AnalysisProgressUpdate0\x01\x12/\n" +
	"\x04Ping\x12\x12.agent.PingRequest\x1a\x13.agent.PongResponseB/Z-github.com/sujithm/ghost-debugger/proto/agentb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_agent_proto_goTypes = []any{
	(*AnalysisRequest)(nil),        // 0: agent.AnalysisRequest
	(*AgentFinding)(nil),           // 1: agent.AgentFinding
	(*AnalysisResponse)(nil),       // 2: agent.AnalysisResponse
	(*AnalysisProgressUpdate)(nil), // 3: agent.AnalysisProgressUpdate
	(*PingRequest)(nil),            // 4: agent.PingRequest
	(*PongResponse)(nil),           // 5: agent.PongResponse
}
var file_agent_proto_depIdxs = []int32{
	1, // 0: agent.AnalysisResponse.findings:type_name -> agent.AgentFinding
	0, // 1: agent.AgentService.AnalyzeIncident:input_type -> agent.AnalysisRequest
	0, // 2: agent.AgentService.AnalyzeIncidentWithProgress:input_type -> agent.AnalysisRequest
	4, // 3: agent.AgentService.Ping:input_type -> agent.PingRequest
	2, // 4: agent.AgentService.AnalyzeIncident:output_type -> agent.AnalysisResponse
	3, // 5: agent.AgentService.AnalyzeIncidentWithProgress:output_type -> agent.AnalysisProgressUpdate
	5, // 6: agent.AgentService.Ping:output_type -> agent.PongResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
